//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.CanalManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="CanalManagerBeanService.CanalManager")]
    public interface CanalManager {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.creerResponse creer(PolyTweetWPF.CanalManagerBeanService.creer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimer", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public supprimer() {
        }
        
        public supprimer(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerResponse() {
        }
        
        public supprimerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public enum typeCanal {
        
        /// <remarks/>
        PUBLIC,
        
        /// <remarks/>
        PRIVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class canal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private utilisateur[] abonnesField;
        
        private utilisateur[] attenteField;
        
        private message[] messagesField;
        
        private utilisateur[] moderateursField;
        
        private utilisateur[] proprietairesField;
        
        private string tagField;
        
        private typeCanal typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public utilisateur[] abonnes {
            get {
                return this.abonnesField;
            }
            set {
                this.abonnesField = value;
                this.RaisePropertyChanged("abonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public utilisateur[] attente {
            get {
                return this.attenteField;
            }
            set {
                this.attenteField = value;
                this.RaisePropertyChanged("attente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("moderateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public utilisateur[] moderateurs {
            get {
                return this.moderateursField;
            }
            set {
                this.moderateursField = value;
                this.RaisePropertyChanged("moderateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public utilisateur[] proprietaires {
            get {
                return this.proprietairesField;
            }
            set {
                this.proprietairesField = value;
                this.RaisePropertyChanged("proprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public typeCanal type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class utilisateur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private canal[] canalAbonnesField;
        
        private canal[] canalAttenteField;
        
        private canal[] canalModerateursField;
        
        private canal[] canalProprietairesField;
        
        private string loginField;
        
        private message[] messagesEnvoyesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAbonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public canal[] canalAbonnes {
            get {
                return this.canalAbonnesField;
            }
            set {
                this.canalAbonnesField = value;
                this.RaisePropertyChanged("canalAbonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAttente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public canal[] canalAttente {
            get {
                return this.canalAttenteField;
            }
            set {
                this.canalAttenteField = value;
                this.RaisePropertyChanged("canalAttente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalModerateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public canal[] canalModerateurs {
            get {
                return this.canalModerateursField;
            }
            set {
                this.canalModerateursField = value;
                this.RaisePropertyChanged("canalModerateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalProprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public canal[] canalProprietaires {
            get {
                return this.canalProprietairesField;
            }
            set {
                this.canalProprietairesField = value;
                this.RaisePropertyChanged("canalProprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messagesEnvoyes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public message[] messagesEnvoyes {
            get {
                return this.messagesEnvoyesField;
            }
            set {
                this.messagesEnvoyesField = value;
                this.RaisePropertyChanged("messagesEnvoyes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creer", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class creer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.CanalManagerBeanService.typeCanal arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public creer() {
        }
        
        public creer(string arg0, PolyTweetWPF.CanalManagerBeanService.typeCanal arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creerResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class creerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.CanalManagerBeanService.canal @return;
        
        public creerResponse() {
        }
        
        public creerResponse(PolyTweetWPF.CanalManagerBeanService.canal @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessage", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.CanalManagerBeanService.message arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.CanalManagerBeanService.canal arg1;
        
        public ajouterMessage() {
        }
        
        public ajouterMessage(PolyTweetWPF.CanalManagerBeanService.message arg0, PolyTweetWPF.CanalManagerBeanService.canal arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessageResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ajouterMessageResponse() {
        }
        
        public ajouterMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CanalManagerChannel : PolyTweetWPF.CanalManagerBeanService.CanalManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CanalManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.CanalManagerBeanService.CanalManager>, PolyTweetWPF.CanalManagerBeanService.CanalManager {
        
        public CanalManagerClient() {
        }
        
        public CanalManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimer(request);
        }
        
        public bool supprimer(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.supprimerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.creerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.creer(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creer(request);
        }
        
        public PolyTweetWPF.CanalManagerBeanService.canal creer(string arg0, PolyTweetWPF.CanalManagerBeanService.typeCanal arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.CanalManagerBeanService.creerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(string arg0, PolyTweetWPF.CanalManagerBeanService.typeCanal arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessage(request);
        }
        
        public bool ajouterMessage(PolyTweetWPF.CanalManagerBeanService.message arg0, PolyTweetWPF.CanalManagerBeanService.canal arg1) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.message arg0, PolyTweetWPF.CanalManagerBeanService.canal arg1) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessageAsync(inValue);
        }
    }
}
