//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.CanalManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="CanalManagerBeanService.CanalManager")]
    public interface CanalManager {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg0 de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg1 de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse supprimerMessage(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg0 de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PolyTweetWPF.CanalManagerBeanService.creerResponse creer(PolyTweetWPF.CanalManagerBeanService.creer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg1 de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class supprimer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="supprimer", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.supprimerBody Body;
        
        public supprimer() {
        }
        
        public supprimer(PolyTweetWPF.CanalManagerBeanService.supprimerBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class supprimerBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public supprimerBody() {
        }
        
        public supprimerBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class supprimerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="supprimerResponse", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.supprimerResponseBody Body;
        
        public supprimerResponse() {
        }
        
        public supprimerResponse(PolyTweetWPF.CanalManagerBeanService.supprimerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class supprimerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public supprimerResponseBody() {
        }
        
        public supprimerResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class supprimerMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="supprimerMessage", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.supprimerMessageBody Body;
        
        public supprimerMessage() {
        }
        
        public supprimerMessage(PolyTweetWPF.CanalManagerBeanService.supprimerMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class supprimerMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public supprimerMessageBody() {
        }
        
        public supprimerMessageBody(long arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class supprimerMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="supprimerMessageResponse", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponseBody Body;
        
        public supprimerMessageResponse() {
        }
        
        public supprimerMessageResponse(PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class supprimerMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public supprimerMessageResponseBody() {
        }
        
        public supprimerMessageResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creer", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.creerBody Body;
        
        public creer() {
        }
        
        public creer(PolyTweetWPF.CanalManagerBeanService.creerBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creerBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public creerBody() {
        }
        
        public creerBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creerResponse", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.creerResponseBody Body;
        
        public creerResponse() {
        }
        
        public creerResponse(PolyTweetWPF.CanalManagerBeanService.creerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class creerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public creerResponseBody() {
        }
        
        public creerResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterMessage", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.ajouterMessageBody Body;
        
        public ajouterMessage() {
        }
        
        public ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ajouterMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public ajouterMessageBody() {
        }
        
        public ajouterMessageBody(long arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterMessageResponse", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponseBody Body;
        
        public ajouterMessageResponse() {
        }
        
        public ajouterMessageResponse(PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ajouterMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ajouterMessageResponseBody() {
        }
        
        public ajouterMessageResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CanalManagerChannel : PolyTweetWPF.CanalManagerBeanService.CanalManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CanalManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.CanalManagerBeanService.CanalManager>, PolyTweetWPF.CanalManagerBeanService.CanalManager {
        
        public CanalManagerClient() {
        }
        
        public CanalManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimer(request);
        }
        
        public bool supprimer(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.supprimerBody();
            inValue.Body.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.supprimerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimer(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.supprimerBody();
            inValue.Body.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerMessage(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessage(request);
        }
        
        public bool supprimerMessage(long arg0, string arg1) {
            PolyTweetWPF.CanalManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.CanalManagerBeanService.supprimerMessage();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.supprimerMessageBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerMessageAsync(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(long arg0, string arg1) {
            PolyTweetWPF.CanalManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.CanalManagerBeanService.supprimerMessage();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.supprimerMessageBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.creerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.creer(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creer(request);
        }
        
        public string creer(string arg0, string arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.creerBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            PolyTweetWPF.CanalManagerBeanService.creerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creer(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(string arg0, string arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.creerBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessage(request);
        }
        
        public bool ajouterMessage(long arg0, string arg1) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.ajouterMessageBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(long arg0, string arg1) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.Body = new PolyTweetWPF.CanalManagerBeanService.ajouterMessageBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessageAsync(inValue);
        }
    }
}
