//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.CanalManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="CanalManagerBeanService.CanalManager")]
    public interface CanalManager {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse afficherTagByAbonne(PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse> afficherTagByAbonneAsync(PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse supprimerMessage(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.canalExisteResponse canalExiste(PolyTweetWPF.CanalManagerBeanService.canalExiste request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.canalExisteResponse> canalExisteAsync(PolyTweetWPF.CanalManagerBeanService.canalExiste request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse afficherTagByType(PolyTweetWPF.CanalManagerBeanService.afficherTagByType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse> afficherTagByTypeAsync(PolyTweetWPF.CanalManagerBeanService.afficherTagByType request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.CanalManagerBeanService.creerResponse creer(PolyTweetWPF.CanalManagerBeanService.creer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTagByAbonne", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTagByAbonne {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public afficherTagByAbonne() {
        }
        
        public afficherTagByAbonne(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTagByAbonneResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTagByAbonneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public afficherTagByAbonneResponse() {
        }
        
        public afficherTagByAbonneResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimer", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public supprimer() {
        }
        
        public supprimer(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerResponse() {
        }
        
        public supprimerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerMessage", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public supprimerMessage() {
        }
        
        public supprimerMessage(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerMessageResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerMessageResponse() {
        }
        
        public supprimerMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canalExiste", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class canalExiste {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public canalExiste() {
        }
        
        public canalExiste(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canalExisteResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class canalExisteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public canalExisteResponse() {
        }
        
        public canalExisteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessage", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public ajouterMessage() {
        }
        
        public ajouterMessage(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessageResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ajouterMessageResponse() {
        }
        
        public ajouterMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTagByType", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTagByType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public afficherTagByType() {
        }
        
        public afficherTagByType(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTagByTypeResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTagByTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public afficherTagByTypeResponse() {
        }
        
        public afficherTagByTypeResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creer", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class creer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public creer() {
        }
        
        public creer(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creerResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class creerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public creerResponse() {
        }
        
        public creerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CanalManagerChannel : PolyTweetWPF.CanalManagerBeanService.CanalManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CanalManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.CanalManagerBeanService.CanalManager>, PolyTweetWPF.CanalManagerBeanService.CanalManager {
        
        public CanalManagerClient() {
        }
        
        public CanalManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CanalManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.afficherTagByAbonne(PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne request) {
            return base.Channel.afficherTagByAbonne(request);
        }
        
        public string[] afficherTagByAbonne(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne inValue = new PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).afficherTagByAbonne(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.afficherTagByAbonneAsync(PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne request) {
            return base.Channel.afficherTagByAbonneAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonneResponse> afficherTagByAbonneAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne inValue = new PolyTweetWPF.CanalManagerBeanService.afficherTagByAbonne();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).afficherTagByAbonneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.supprimerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimer(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimer(request);
        }
        
        public bool supprimer(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.supprimerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerAsync(PolyTweetWPF.CanalManagerBeanService.supprimer request) {
            return base.Channel.supprimerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerResponse> supprimerAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimer inValue = new PolyTweetWPF.CanalManagerBeanService.supprimer();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerMessage(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessage(request);
        }
        
        public bool supprimerMessage(long arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.CanalManagerBeanService.supprimerMessage();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.supprimerMessageAsync(PolyTweetWPF.CanalManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(long arg0) {
            PolyTweetWPF.CanalManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.CanalManagerBeanService.supprimerMessage();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).supprimerMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.canalExisteResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.canalExiste(PolyTweetWPF.CanalManagerBeanService.canalExiste request) {
            return base.Channel.canalExiste(request);
        }
        
        public bool canalExiste(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.canalExiste inValue = new PolyTweetWPF.CanalManagerBeanService.canalExiste();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.canalExisteResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).canalExiste(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.canalExisteResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.canalExisteAsync(PolyTweetWPF.CanalManagerBeanService.canalExiste request) {
            return base.Channel.canalExisteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.canalExisteResponse> canalExisteAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.canalExiste inValue = new PolyTweetWPF.CanalManagerBeanService.canalExiste();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).canalExisteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessage(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessage(request);
        }
        
        public bool ajouterMessage(long arg0) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.ajouterMessageAsync(PolyTweetWPF.CanalManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(long arg0) {
            PolyTweetWPF.CanalManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.CanalManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).ajouterMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.afficherTagByType(PolyTweetWPF.CanalManagerBeanService.afficherTagByType request) {
            return base.Channel.afficherTagByType(request);
        }
        
        public string[] afficherTagByType(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.afficherTagByType inValue = new PolyTweetWPF.CanalManagerBeanService.afficherTagByType();
            inValue.arg0 = arg0;
            PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).afficherTagByType(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.afficherTagByTypeAsync(PolyTweetWPF.CanalManagerBeanService.afficherTagByType request) {
            return base.Channel.afficherTagByTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.afficherTagByTypeResponse> afficherTagByTypeAsync(string arg0) {
            PolyTweetWPF.CanalManagerBeanService.afficherTagByType inValue = new PolyTweetWPF.CanalManagerBeanService.afficherTagByType();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).afficherTagByTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.CanalManagerBeanService.creerResponse PolyTweetWPF.CanalManagerBeanService.CanalManager.creer(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creer(request);
        }
        
        public string creer(string arg0, string arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.CanalManagerBeanService.creerResponse retVal = ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> PolyTweetWPF.CanalManagerBeanService.CanalManager.creerAsync(PolyTweetWPF.CanalManagerBeanService.creer request) {
            return base.Channel.creerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.CanalManagerBeanService.creerResponse> creerAsync(string arg0, string arg1, string arg2) {
            PolyTweetWPF.CanalManagerBeanService.creer inValue = new PolyTweetWPF.CanalManagerBeanService.creer();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.CanalManagerBeanService.CanalManager)(this)).creerAsync(inValue);
        }
    }
}
