//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.UtilisateurManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="UtilisateurManagerBeanService.UtilisateurManager")]
    public interface UtilisateurManager {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse demandeAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse> demandeAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse delete(PolyTweetWPF.UtilisateurManagerBeanService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse> deleteAsync(PolyTweetWPF.UtilisateurManagerBeanService.delete request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse consulterMessages(PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse> consulterMessagesAsync(PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse supprimerModerateur(PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse> supprimerModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.createResponse create(PolyTweetWPF.UtilisateurManagerBeanService.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.createResponse> createAsync(PolyTweetWPF.UtilisateurManagerBeanService.create request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse ajouterMessage(PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse accepterAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse> accepterAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse ajouterModerateur(PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse> ajouterModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse supprimerProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse> supprimerProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse supprimerMessage(PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse ajouterProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse> ajouterProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse refuserAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse> refuserAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class utilisateur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private canal[] canalAbonnesField;
        
        private canal[] canalAttenteField;
        
        private canal[] canalModerateursField;
        
        private canal[] canalProprietairesField;
        
        private string loginField;
        
        private message[] messagesEnvoyesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAbonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public canal[] canalAbonnes {
            get {
                return this.canalAbonnesField;
            }
            set {
                this.canalAbonnesField = value;
                this.RaisePropertyChanged("canalAbonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAttente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public canal[] canalAttente {
            get {
                return this.canalAttenteField;
            }
            set {
                this.canalAttenteField = value;
                this.RaisePropertyChanged("canalAttente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalModerateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public canal[] canalModerateurs {
            get {
                return this.canalModerateursField;
            }
            set {
                this.canalModerateursField = value;
                this.RaisePropertyChanged("canalModerateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalProprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public canal[] canalProprietaires {
            get {
                return this.canalProprietairesField;
            }
            set {
                this.canalProprietairesField = value;
                this.RaisePropertyChanged("canalProprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messagesEnvoyes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public message[] messagesEnvoyes {
            get {
                return this.messagesEnvoyesField;
            }
            set {
                this.messagesEnvoyesField = value;
                this.RaisePropertyChanged("messagesEnvoyes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class canal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private utilisateur[] abonnesField;
        
        private utilisateur[] attenteField;
        
        private message[] messagesField;
        
        private utilisateur[] moderateursField;
        
        private utilisateur[] proprietairesField;
        
        private string tagField;
        
        private typeCanal typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public utilisateur[] abonnes {
            get {
                return this.abonnesField;
            }
            set {
                this.abonnesField = value;
                this.RaisePropertyChanged("abonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public utilisateur[] attente {
            get {
                return this.attenteField;
            }
            set {
                this.attenteField = value;
                this.RaisePropertyChanged("attente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("moderateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public utilisateur[] moderateurs {
            get {
                return this.moderateursField;
            }
            set {
                this.moderateursField = value;
                this.RaisePropertyChanged("moderateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public utilisateur[] proprietaires {
            get {
                return this.proprietairesField;
            }
            set {
                this.proprietairesField = value;
                this.RaisePropertyChanged("proprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public typeCanal type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public enum typeCanal {
        
        /// <remarks/>
        PUBLIC,
        
        /// <remarks/>
        PRIVE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="demandeAbonnement", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class demandeAbonnement {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public demandeAbonnement() {
        }
        
        public demandeAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="demandeAbonnementResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class demandeAbonnementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public demandeAbonnementResponse() {
        }
        
        public demandeAbonnementResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public delete() {
        }
        
        public delete(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consulterMessages", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class consulterMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public consulterMessages() {
        }
        
        public consulterMessages(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consulterMessagesResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class consulterMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.message[] @return;
        
        public consulterMessagesResponse() {
        }
        
        public consulterMessagesResponse(PolyTweetWPF.UtilisateurManagerBeanService.message[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerModerateur", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerModerateur {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public supprimerModerateur() {
        }
        
        public supprimerModerateur(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerModerateurResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerModerateurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerModerateurResponse() {
        }
        
        public supprimerModerateurResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public create() {
        }
        
        public create(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur @return;
        
        public createResponse() {
        }
        
        public createResponse(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessage", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.message arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public ajouterMessage() {
        }
        
        public ajouterMessage(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterMessageResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ajouterMessageResponse() {
        }
        
        public ajouterMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="accepterAbonnement", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class accepterAbonnement {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public accepterAbonnement() {
        }
        
        public accepterAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="accepterAbonnementResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class accepterAbonnementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public accepterAbonnementResponse() {
        }
        
        public accepterAbonnementResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterModerateur", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterModerateur {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public ajouterModerateur() {
        }
        
        public ajouterModerateur(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterModerateurResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterModerateurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ajouterModerateurResponse() {
        }
        
        public ajouterModerateurResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerProprietaire", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerProprietaire {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public supprimerProprietaire() {
        }
        
        public supprimerProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerProprietaireResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerProprietaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerProprietaireResponse() {
        }
        
        public supprimerProprietaireResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerMessage", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.message arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public supprimerMessage() {
        }
        
        public supprimerMessage(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerMessageResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class supprimerMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public supprimerMessageResponse() {
        }
        
        public supprimerMessageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterProprietaire", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterProprietaire {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public ajouterProprietaire() {
        }
        
        public ajouterProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterProprietaireResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class ajouterProprietaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ajouterProprietaireResponse() {
        }
        
        public ajouterProprietaireResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refuserAbonnement", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class refuserAbonnement {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public refuserAbonnement() {
        }
        
        public refuserAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refuserAbonnementResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class refuserAbonnementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public refuserAbonnementResponse() {
        }
        
        public refuserAbonnementResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilisateurManagerChannel : PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilisateurManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager>, PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager {
        
        public UtilisateurManagerClient() {
        }
        
        public UtilisateurManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilisateurManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilisateurManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilisateurManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.demandeAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement request) {
            return base.Channel.demandeAbonnement(request);
        }
        
        public bool demandeAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).demandeAbonnement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.demandeAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement request) {
            return base.Channel.demandeAbonnementAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnementResponse> demandeAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.demandeAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).demandeAbonnementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.delete(PolyTweetWPF.UtilisateurManagerBeanService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string arg0) {
            PolyTweetWPF.UtilisateurManagerBeanService.delete inValue = new PolyTweetWPF.UtilisateurManagerBeanService.delete();
            inValue.arg0 = arg0;
            PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.deleteAsync(PolyTweetWPF.UtilisateurManagerBeanService.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.deleteResponse> deleteAsync(string arg0) {
            PolyTweetWPF.UtilisateurManagerBeanService.delete inValue = new PolyTweetWPF.UtilisateurManagerBeanService.delete();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.consulterMessages(PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages request) {
            return base.Channel.consulterMessages(request);
        }
        
        public PolyTweetWPF.UtilisateurManagerBeanService.message[] consulterMessages(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages inValue = new PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).consulterMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.consulterMessagesAsync(PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages request) {
            return base.Channel.consulterMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.consulterMessagesResponse> consulterMessagesAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, string arg1) {
            PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages inValue = new PolyTweetWPF.UtilisateurManagerBeanService.consulterMessages();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).consulterMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerModerateur(PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur request) {
            return base.Channel.supprimerModerateur(request);
        }
        
        public bool supprimerModerateur(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerModerateur(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur request) {
            return base.Channel.supprimerModerateurAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateurResponse> supprimerModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerModerateur();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerModerateurAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.createResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.create(PolyTweetWPF.UtilisateurManagerBeanService.create request) {
            return base.Channel.create(request);
        }
        
        public PolyTweetWPF.UtilisateurManagerBeanService.utilisateur create(string arg0) {
            PolyTweetWPF.UtilisateurManagerBeanService.create inValue = new PolyTweetWPF.UtilisateurManagerBeanService.create();
            inValue.arg0 = arg0;
            PolyTweetWPF.UtilisateurManagerBeanService.createResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).create(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.createResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.createAsync(PolyTweetWPF.UtilisateurManagerBeanService.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.createResponse> createAsync(string arg0) {
            PolyTweetWPF.UtilisateurManagerBeanService.create inValue = new PolyTweetWPF.UtilisateurManagerBeanService.create();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterMessage(PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessage(request);
        }
        
        public bool ajouterMessage(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage request) {
            return base.Channel.ajouterMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessageResponse> ajouterMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.accepterAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement request) {
            return base.Channel.accepterAbonnement(request);
        }
        
        public bool accepterAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).accepterAbonnement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.accepterAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement request) {
            return base.Channel.accepterAbonnementAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnementResponse> accepterAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.accepterAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).accepterAbonnementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterModerateur(PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur request) {
            return base.Channel.ajouterModerateur(request);
        }
        
        public bool ajouterModerateur(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterModerateur(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur request) {
            return base.Channel.ajouterModerateurAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateurResponse> ajouterModerateurAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterModerateur();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterModerateurAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire request) {
            return base.Channel.supprimerProprietaire(request);
        }
        
        public bool supprimerProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerProprietaire(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire request) {
            return base.Channel.supprimerProprietaireAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaireResponse> supprimerProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerProprietaire();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerProprietaireAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerMessage(PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessage(request);
        }
        
        public bool supprimerMessage(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.supprimerMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage request) {
            return base.Channel.supprimerMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessageResponse> supprimerMessageAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.message arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage inValue = new PolyTweetWPF.UtilisateurManagerBeanService.supprimerMessage();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).supprimerMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire request) {
            return base.Channel.ajouterProprietaire(request);
        }
        
        public bool ajouterProprietaire(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterProprietaire(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.ajouterProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire request) {
            return base.Channel.ajouterProprietaireAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaireResponse> ajouterProprietaireAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire inValue = new PolyTweetWPF.UtilisateurManagerBeanService.ajouterProprietaire();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).ajouterProprietaireAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.refuserAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement request) {
            return base.Channel.refuserAbonnement(request);
        }
        
        public bool refuserAbonnement(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse retVal = ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).refuserAbonnement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse> PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager.refuserAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement request) {
            return base.Channel.refuserAbonnementAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnementResponse> refuserAbonnementAsync(PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg0, PolyTweetWPF.UtilisateurManagerBeanService.utilisateur arg1, string arg2) {
            PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement inValue = new PolyTweetWPF.UtilisateurManagerBeanService.refuserAbonnement();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.UtilisateurManagerBeanService.UtilisateurManager)(this)).refuserAbonnementAsync(inValue);
        }
    }
}
