//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.MessageManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="MessageManagerBeanService.MessageManager")]
    public interface MessageManager {
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms d'une partie du message  ne correspond pas à la valeur par défaut (http://domain.j2e/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.deleteResponse delete(PolyTweetWPF.MessageManagerBeanService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> deleteAsync(PolyTweetWPF.MessageManagerBeanService.delete request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg0 de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PolyTweetWPF.MessageManagerBeanService.createResponse create(PolyTweetWPF.MessageManagerBeanService.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> createAsync(PolyTweetWPF.MessageManagerBeanService.create request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        public delete() {
        }
        
        public delete(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.MessageManagerBeanService.createBody Body;
        
        public create() {
        }
        
        public create(PolyTweetWPF.MessageManagerBeanService.createBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public createBody() {
        }
        
        public createBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createResponse", Namespace="http://domain.j2e/", Order=0)]
        public PolyTweetWPF.MessageManagerBeanService.createResponseBody Body;
        
        public createResponse() {
        }
        
        public createResponse(PolyTweetWPF.MessageManagerBeanService.createResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long @return;
        
        public createResponseBody() {
        }
        
        public createResponseBody(long @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageManagerChannel : PolyTweetWPF.MessageManagerBeanService.MessageManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.MessageManagerBeanService.MessageManager>, PolyTweetWPF.MessageManagerBeanService.MessageManager {
        
        public MessageManagerClient() {
        }
        
        public MessageManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.deleteResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.delete(PolyTweetWPF.MessageManagerBeanService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.delete inValue = new PolyTweetWPF.MessageManagerBeanService.delete();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.deleteResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.deleteAsync(PolyTweetWPF.MessageManagerBeanService.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> deleteAsync(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.delete inValue = new PolyTweetWPF.MessageManagerBeanService.delete();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.createResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.create(PolyTweetWPF.MessageManagerBeanService.create request) {
            return base.Channel.create(request);
        }
        
        public long create(string arg0, string arg1, string arg2) {
            PolyTweetWPF.MessageManagerBeanService.create inValue = new PolyTweetWPF.MessageManagerBeanService.create();
            inValue.Body = new PolyTweetWPF.MessageManagerBeanService.createBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            PolyTweetWPF.MessageManagerBeanService.createResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).create(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.createAsync(PolyTweetWPF.MessageManagerBeanService.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> createAsync(string arg0, string arg1, string arg2) {
            PolyTweetWPF.MessageManagerBeanService.create inValue = new PolyTweetWPF.MessageManagerBeanService.create();
            inValue.Body = new PolyTweetWPF.MessageManagerBeanService.createBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).createAsync(inValue);
        }
    }
}
