//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.MessageManagerBeanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="MessageManagerBeanService.MessageManager")]
    public interface MessageManager {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse afficherIdByTag(PolyTweetWPF.MessageManagerBeanService.afficherIdByTag request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse> afficherIdByTagAsync(PolyTweetWPF.MessageManagerBeanService.afficherIdByTag request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse afficherDateByID(PolyTweetWPF.MessageManagerBeanService.afficherDateByID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse> afficherDateByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherDateByID request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.deleteResponse delete(PolyTweetWPF.MessageManagerBeanService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> deleteAsync(PolyTweetWPF.MessageManagerBeanService.delete request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse afficherTexteByID(PolyTweetWPF.MessageManagerBeanService.afficherTexteByID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse> afficherTexteByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherTexteByID request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.createResponse create(PolyTweetWPF.MessageManagerBeanService.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> createAsync(PolyTweetWPF.MessageManagerBeanService.create request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse afficherAuteurByID(PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse> afficherAuteurByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherIdByTag", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherIdByTag {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public afficherIdByTag() {
        }
        
        public afficherIdByTag(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherIdByTagResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherIdByTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] @return;
        
        public afficherIdByTagResponse() {
        }
        
        public afficherIdByTagResponse(long[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherDateByID", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherDateByID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public afficherDateByID() {
        }
        
        public afficherDateByID(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherDateByIDResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherDateByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public afficherDateByIDResponse() {
        }
        
        public afficherDateByIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public delete() {
        }
        
        public delete(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTexteByID", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTexteByID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public afficherTexteByID() {
        }
        
        public afficherTexteByID(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherTexteByIDResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherTexteByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public afficherTexteByIDResponse() {
        }
        
        public afficherTexteByIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public create() {
        }
        
        public create(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public createResponse() {
        }
        
        public createResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherAuteurByID", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherAuteurByID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public afficherAuteurByID() {
        }
        
        public afficherAuteurByID(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="afficherAuteurByIDResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class afficherAuteurByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public afficherAuteurByIDResponse() {
        }
        
        public afficherAuteurByIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageManagerChannel : PolyTweetWPF.MessageManagerBeanService.MessageManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageManagerClient : System.ServiceModel.ClientBase<PolyTweetWPF.MessageManagerBeanService.MessageManager>, PolyTweetWPF.MessageManagerBeanService.MessageManager {
        
        public MessageManagerClient() {
        }
        
        public MessageManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherIdByTag(PolyTweetWPF.MessageManagerBeanService.afficherIdByTag request) {
            return base.Channel.afficherIdByTag(request);
        }
        
        public long[] afficherIdByTag(string arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherIdByTag inValue = new PolyTweetWPF.MessageManagerBeanService.afficherIdByTag();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherIdByTag(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherIdByTagAsync(PolyTweetWPF.MessageManagerBeanService.afficherIdByTag request) {
            return base.Channel.afficherIdByTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherIdByTagResponse> afficherIdByTagAsync(string arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherIdByTag inValue = new PolyTweetWPF.MessageManagerBeanService.afficherIdByTag();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherIdByTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherDateByID(PolyTweetWPF.MessageManagerBeanService.afficherDateByID request) {
            return base.Channel.afficherDateByID(request);
        }
        
        public string afficherDateByID(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherDateByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherDateByID();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherDateByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherDateByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherDateByID request) {
            return base.Channel.afficherDateByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherDateByIDResponse> afficherDateByIDAsync(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherDateByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherDateByID();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherDateByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.deleteResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.delete(PolyTweetWPF.MessageManagerBeanService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.delete inValue = new PolyTweetWPF.MessageManagerBeanService.delete();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.deleteResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.deleteAsync(PolyTweetWPF.MessageManagerBeanService.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.deleteResponse> deleteAsync(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.delete inValue = new PolyTweetWPF.MessageManagerBeanService.delete();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherTexteByID(PolyTweetWPF.MessageManagerBeanService.afficherTexteByID request) {
            return base.Channel.afficherTexteByID(request);
        }
        
        public string afficherTexteByID(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherTexteByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherTexteByID();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherTexteByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherTexteByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherTexteByID request) {
            return base.Channel.afficherTexteByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherTexteByIDResponse> afficherTexteByIDAsync(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherTexteByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherTexteByID();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherTexteByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.createResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.create(PolyTweetWPF.MessageManagerBeanService.create request) {
            return base.Channel.create(request);
        }
        
        public long create(string arg0, string arg1, string arg2) {
            PolyTweetWPF.MessageManagerBeanService.create inValue = new PolyTweetWPF.MessageManagerBeanService.create();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PolyTweetWPF.MessageManagerBeanService.createResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).create(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.createAsync(PolyTweetWPF.MessageManagerBeanService.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.createResponse> createAsync(string arg0, string arg1, string arg2) {
            PolyTweetWPF.MessageManagerBeanService.create inValue = new PolyTweetWPF.MessageManagerBeanService.create();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherAuteurByID(PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID request) {
            return base.Channel.afficherAuteurByID(request);
        }
        
        public string afficherAuteurByID(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID();
            inValue.arg0 = arg0;
            PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse retVal = ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherAuteurByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse> PolyTweetWPF.MessageManagerBeanService.MessageManager.afficherAuteurByIDAsync(PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID request) {
            return base.Channel.afficherAuteurByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.MessageManagerBeanService.afficherAuteurByIDResponse> afficherAuteurByIDAsync(long arg0) {
            PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID inValue = new PolyTweetWPF.MessageManagerBeanService.afficherAuteurByID();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.MessageManagerBeanService.MessageManager)(this)).afficherAuteurByIDAsync(inValue);
        }
    }
}
