//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTweetWPF.UtilisateurFinderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://domain.j2e/", ConfigurationName="UtilisateurFinderService.UtilisateurFinder")]
    public interface UtilisateurFinder {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse findUtilisateurByLogin(PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse> findUtilisateurByLoginAsync(PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class utilisateur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private canal[] canalAbonnesField;
        
        private canal[] canalAttenteField;
        
        private canal[] canalModerateursField;
        
        private canal[] canalProprietairesField;
        
        private string loginField;
        
        private message[] messagesEnvoyesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAbonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public canal[] canalAbonnes {
            get {
                return this.canalAbonnesField;
            }
            set {
                this.canalAbonnesField = value;
                this.RaisePropertyChanged("canalAbonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalAttente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public canal[] canalAttente {
            get {
                return this.canalAttenteField;
            }
            set {
                this.canalAttenteField = value;
                this.RaisePropertyChanged("canalAttente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalModerateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public canal[] canalModerateurs {
            get {
                return this.canalModerateursField;
            }
            set {
                this.canalModerateursField = value;
                this.RaisePropertyChanged("canalModerateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canalProprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public canal[] canalProprietaires {
            get {
                return this.canalProprietairesField;
            }
            set {
                this.canalProprietairesField = value;
                this.RaisePropertyChanged("canalProprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messagesEnvoyes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public message[] messagesEnvoyes {
            get {
                return this.messagesEnvoyesField;
            }
            set {
                this.messagesEnvoyesField = value;
                this.RaisePropertyChanged("messagesEnvoyes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class canal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private utilisateur[] abonnesField;
        
        private utilisateur[] attenteField;
        
        private message[] messagesField;
        
        private utilisateur[] moderateursField;
        
        private utilisateur[] proprietairesField;
        
        private string tagField;
        
        private typeCanal typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abonnes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public utilisateur[] abonnes {
            get {
                return this.abonnesField;
            }
            set {
                this.abonnesField = value;
                this.RaisePropertyChanged("abonnes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public utilisateur[] attente {
            get {
                return this.attenteField;
            }
            set {
                this.attenteField = value;
                this.RaisePropertyChanged("attente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("moderateurs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public utilisateur[] moderateurs {
            get {
                return this.moderateursField;
            }
            set {
                this.moderateursField = value;
                this.RaisePropertyChanged("moderateurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proprietaires", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public utilisateur[] proprietaires {
            get {
                return this.proprietairesField;
            }
            set {
                this.proprietairesField = value;
                this.RaisePropertyChanged("proprietaires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public typeCanal type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.j2e/")]
    public enum typeCanal {
        
        /// <remarks/>
        PUBLIC,
        
        /// <remarks/>
        PRIVE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUtilisateurByLogin", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class findUtilisateurByLogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findUtilisateurByLogin() {
        }
        
        public findUtilisateurByLogin(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUtilisateurByLoginResponse", WrapperNamespace="http://domain.j2e/", IsWrapped=true)]
    public partial class findUtilisateurByLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://domain.j2e/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PolyTweetWPF.UtilisateurFinderService.utilisateur @return;
        
        public findUtilisateurByLoginResponse() {
        }
        
        public findUtilisateurByLoginResponse(PolyTweetWPF.UtilisateurFinderService.utilisateur @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilisateurFinderChannel : PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilisateurFinderClient : System.ServiceModel.ClientBase<PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder>, PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder {
        
        public UtilisateurFinderClient() {
        }
        
        public UtilisateurFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilisateurFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilisateurFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilisateurFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder.findUtilisateurByLogin(PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin request) {
            return base.Channel.findUtilisateurByLogin(request);
        }
        
        public PolyTweetWPF.UtilisateurFinderService.utilisateur findUtilisateurByLogin(string arg0) {
            PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin inValue = new PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin();
            inValue.arg0 = arg0;
            PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse retVal = ((PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder)(this)).findUtilisateurByLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse> PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder.findUtilisateurByLoginAsync(PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin request) {
            return base.Channel.findUtilisateurByLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLoginResponse> findUtilisateurByLoginAsync(string arg0) {
            PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin inValue = new PolyTweetWPF.UtilisateurFinderService.findUtilisateurByLogin();
            inValue.arg0 = arg0;
            return ((PolyTweetWPF.UtilisateurFinderService.UtilisateurFinder)(this)).findUtilisateurByLoginAsync(inValue);
        }
    }
}
